apiVersion: v1
kind: Secret
metadata:
  name: rag-bot-secrets
type: Opaque
stringData:
  AZURE_OPENAI_ENDPOINT: {{ .Values.env.AZURE_OPENAI_ENDPOINT | quote }}
  OPENAI_API_VERSION: {{ .Values.env.OPENAI_API_VERSION | quote }}
  AZURE_OPENAI_API_KEY: {{ .Values.env.AZURE_OPENAI_API_KEY | quote }}
  uri: {{ .Values.env.uri | quote }}
